### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by 000exploit** [DaKnig/DewDuct#6]
I'm too lazy to do everything manually, I just want to install and run software, not build. I think there's no point in describing what flatpak/flathub is and why it's good for end users. Just pack it in flatpak in the near future, since your project has appeared on TWIG.

**Comment by gnuntoo** [comment]
Yeah it looks useful for my librem 5. looking forward to trying it out

**Comment by DaKnig** [comment]
Will do!
btw what operating systems you all use? I might provide packages for these

**Comment by 000exploit** [comment]
I can package it myself for Fedora and most of RPM-based systems using COPR. I'm still not sure about the quality of mine spec files, but I can, yes.

**Comment by ibrahim-mu** [comment]
> Will do! btw what operating systems you all use? I might provide packages for these

An Arch-based distro, so an AUR package will be awesome. Or maybe just a flatpak.

**Comment by julianrichen** [comment]
Hello, I played with packaging this for Flatpak as I'm on Fedora Silverblue and everything is (generally) a Flatpak. I'll attach the yaml and steps I used to at least get it to launch, but the current way the app works likely wont work well for Flatpak.

That app spins-up a child process for mpv, which you generally can't do in Flatpak as you'd be escaping the sandbox. You may want to look into embedding the video player. Maybe using the Clapper library mentioned in the [latest](https://thisweek.gnome.org/posts/2024/05/twig-150/) This Week In GNOME (TWIG): https://gitlab.gnome.org/JanGernert/clapper-rs

But then that doesn't account for needing yt-dl/yt-dlp as well... so I'm not sure really the best way to make this work.

Other packaging notes: 

- You have a mix of `null.daknig.dewduct` (metadata) and `null.daknig.DewDuct` (code) for the app-id. The ID should be unified or it can cause dbus issues in flatpak when it tries to match the names. I generated a patch in the steps below to align it for the build file. Not really familiar with making patches so the steps are probably not the optimal way to do it.
- Generally app-ids are suppose to be reverse dns app-ids, in that it's `tld.domain.appname`. `null.daknig` would be the domain `daknig.null`, which isn't valid (to my understanding). So not sure if it would be approved on Flathub. so `com.github.DaKnig.DewDuct` or `io.github.DaKnig.DewDuct` may be better. Info: https://docs.flathub.org/docs/for-app-authors/requirements/#application-id
- I'd remove the `appstreamcli` step you have in the alpine linux build and what I have below. Just make generating the desktop file as part of the version release when you generate the tarball. Packaging appstreamcli was kind of tedious for Flatpak and same will apply for other formats and you'll need to account for it in each package format.

Hopefully this helps as a starting point in your testing. Interesting app with that I played around with so far :)

Build steps
```bash
# Builddir
mkdir -p ~/Projects/DewDuct
cd ~/Projects/DewDuct

# Copy null.daknig.DewDuct.yml to this folder

# Install SDKs and flatpak-builder
flatpak install org.gnome.Sdk//46
flatpak install org.freedesktop.Sdk.Extension.llvm16//23.08
flatpak install org.freedesktop.Sdk.Extension.rust-stable//23.08
flatpak install org.flatpak.Builder

# Clone cargo helpers and sources files (for flatpak-cargo-generator.py)
git clone https://github.com/flatpak/flatpak-builder-tools.git
git clone https://github.com/DaKnig/DewDuct.git

# Needed Python packages for flatpak-cargo-generator.py
python3 -m pip install --upgrade pip
python3 -m pip install aiohttp 
python3 -m pip install toml

# Generate cargo build files for offline build
python3 ./flatpak-builder-tools/cargo/flatpak-cargo-generator.py ./DewDuct/Cargo.lock -o cargo-sources.json

mkdir -p ./patch-files
cp ./DewDuct/data/null.daknig.dewduct.metainfo.xml ./patch-files/null.daknig.dewduct.metainfo.xml
sed -i 's@null.daknig.dewduct@null.daknig.DewDuct@g' ./patch-files/null.daknig.dewduct.metainfo.xml

# Apply patch for app-id
diff -Naru ./DewDuct/data/null.daknig.dewduct.metainfo.xml ./patch-files/null.daknig.dewduct.metainfo.xml > ./meta.patch
sed -i 's@./DewDuct/data@a/data@g' ./meta.patch
sed -i 's@./patch-files@b/data@g' ./meta.patch

# Build package
flatpak run org.flatpak.Builder --user --install --force-clean dewduct-build null.daknig.DewDuct.yml

# Run once installed
flatpak run null.daknig.DewDuct
```

YAML
```yml
id: null.daknig.DewDuct
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
sdk-extensions:
  # See: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable
  - org.freedesktop.Sdk.Extension.rust-stable
  - org.freedesktop.Sdk.Extension.llvm16
command: dewduct
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=fallback-x11
  # Wayland access
  - --socket=wayland
  # Graphics access
  - --device=dri
  # Network access
  - --share=network
  # File access (TBD)
  - --filesystem=host
build-options:
  # See: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable
  append-path: /usr/lib/sdk/rust-stable/bin:/usr/lib/sdk/llvm16/bin
  env:
    CARGO_HOME: /run/build/dewduct/cargo
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: "clang"
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C link-arg=-fuse-ld=/usr/lib/sdk/rust-stable/bin/mold"
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: "clang"
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C link-arg=-fuse-ld=/usr/lib/sdk/rust-stable/bin/mold"
cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
  # Only needed for appstream module, to avoid symbol conflict
  - /lib/debug
  - /lib/libappstream.so*
  - /lib/libxmlb.so*
  - /lib/libyaml.so*
modules:
  # For Build (appstreamcli)
  - name: appstream
    buildsystem: meson
    config-opts:
      - "-Dbuildtype=release"
      - "-Dstemming=false"
      - "-Dgir=false"
      - "-Dapidocs=false"
    cleanup:
      - "/bin/appstreamcli"
    sources:
      - type: git
        url: https://github.com/ximion/appstream.git
        commit: 1ee6af91310f9deb47f3863a7a7ffb22c46bcce6
        tag: v0.16.2
    modules:
      - name: libyaml
        buildsystem: autotools
        sources:
        - type: git
          url: https://github.com/yaml/libyaml.git
          commit: 2c891fc7a770e8ba2fec34fc6b545c672beb37e6
          tag: 0.2.5
      - name: libxmlb
        buildsystem: meson
        config-opts:
          - "-Dbuildtype=release"
          - "-Dintrospection=false"
          - "-Dtests=false"
          - "-Dcli=false"
          - "-Dgtkdoc=false"
        sources:
          - type: git
            url: https://github.com/hughsie/libxmlb.git
            commit: 6191220071233972d798b57841d08e4964952a17
            tag: 0.3.11

  - name: dewduct
    sources:
      - cargo-sources.json
      - type: archive
        url: https://github.com/DaKnig/DewDuct/archive/refs/tags/v0.2.2.tar.gz
        sha256: eb25d630931941f6d2dd0e0057aa28cd1887db8babaa4677b45ed4c90db234a6
      - type: patch
        path: meta.patch
    buildsystem: simple
    build-commands:
      - cargo --offline fetch --manifest-path 'Cargo.toml' --verbose
      - appstreamcli make-desktop-file data/null.daknig.dewduct.metainfo.xml null.daknig.dewduct.desktop
      - cargo --offline build --release --locked --verbose
      - install -Dm755 target/release/dewduct --target-directory=/app/bin
      - install -Dm644 data/null.daknig.dewduct.metainfo.xml /app/share/metainfo/null.daknig.DewDuct.metainfo.xml
      - install -Dm644 null.daknig.dewduct.desktop /app/share/applications/null.daknig.DewDuct.desktop
      
      # Ideally we would do this, move appstreamcli outside of flatpak and and rename the files and ID.
      # - install -Dm644 data/null.daknig.dewduct.metainfo.xml --target-directory=/app/share/metainfo
      # - install -Dm644 data/null.daknig.DewDuct.desktop --target-directory=/app/share/applications
      # - install -Dm644 data/null.daknig.DewDuct.svg --target-directory=/app/share/icons/hicolor/scalable/apps
```
